# Generated by Django 3.0.7 on 2020-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluentapi', '0002_auto_20200614_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html',
            field=models.TextField(blank=True),
        ),
    ]
